services:
  zmk-rokibo:
    image: docker.io/zmkfirmware/zmk-dev-arm:3.5
    volumes:
      - ./root:/root
      - .:/workspaces/zmk
      - ../zmk-config-rokibo:/workspaces/zmk-config
      - ../zmk-modules:/workspaces/zmk-modules
    environment:
      - WORKSPACE_DIR=/workspaces/zmk
    working_dir: /workspaces/zmk
    ports:
      - "13000:3000"
    security_opt:
      - label:disable
    tty: true
    stdin_open: true
    entrypoint: bash /root/entrypoint.sh
